routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/trainings',[App\Http\Controllers\TrainingController::class,'index'])->name('training:index');
Route::get('/trainings/create',[App\Http\Controllers\TrainingController::class,'create'])->name('training:create');
Route::post('/trainings/create',[App\Http\Controllers\TrainingController::class,'store'])->name('training:store');
Route::get('/trainings/{training}',[App\Http\Controllers\TrainingController::class,'show'])->name('training:show');
Route::get('/trainings/{training}/edit',[App\Http\Controllers\TrainingController::class,'edit'])->name('training:edit');
Route::post('/trainings/{training}/edit',[App\Http\Controllers\TrainingController::class,'update'])->name('training:update');
Route::get('/trainings/{training}/delete',[App\Http\Controllers\TrainingController::class,'delete'])->name('training:delete');

Route::get('/users',[App\Http\Controllers\UserController::class,'index']);
Route::view('test', 'admin.layouts.main');

app/Models/Training.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Training extends Model
{
    use HasFactory;
    protected $guarded=['id'];
    public function user()
    {
        return $this->belongsTo('App\Models\User','user_id','id');
    }

    public function getAttachmentUrlAttribute()
    {
        return asset('storage/'.$this->attachment);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function trainings()
    {
        return $this->hasMany('App\Models\Training');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TrainingController.php
<?php

namespace App\Http\Controllers;

use App\Jobs\SendEmailJob;
use App\Mail\TrainingCreatedMail;
use App\Models\Training;
use File;
use Illuminate\Http\Request;
use Mail;
use Session;
use Storage;

class TrainingController extends Controller
{
    //

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        if($request->carian != null){
            $trainings = Training::where('title','like','%'.$request->carian.'%')->paginate(2);
        } else {
            $trainings = Training::with('user')->paginate(2);
        }
        return view('trainings.index', compact('trainings'));
    }

    public function create()
    {
        return view('trainings.create');
    }

    public function store(Request $request)
    {
        //POPO | Plain Old PHP Object
        // $training = new Training();
        // $training->title = $request->title;
        // $training->description = $request->description;
        // $training->user_id = auth()->user()->id;
        // $training->save();

        $user = auth()->user();
        $training = $user->trainings()->create($request->only('title','description'));

        if ($request->hasFile('attachment')) {
            $filename = $training->id.'-'.date('Y-m-d').'.'.$request->attachment->getCLientOriginalExtension();
            $training->update(['attachment'=>$filename]);
            Storage::disk('public')->put($filename,File::get($request->attachment));
        }

        // Mail::send('emails.training-created', [
        //         'title'=>$request->title,
        //         'description'=>$request->description
        //     ], function ($message) {
        //     $message->from(env('MAIL_FROM_ADDRESS'));
        //     $message->sender(env('MAIL_FROM_ADDRESS'), 'Masibai');
        //     $message->to('AhYie@hellsystem.com.my', 'Dragon of Pasir Mas');
        //     $message->subject('Resignation Letter');
        // });

        // Mail::to('AhYieCekci@hellsystem.com')->send(new TrainingCreatedMail($training));

        dispatch(new SendEmailJob($training));

        return redirect(Route('training:index'))->with([
            'alert-type'=>'alert-primary',
            'alert'=>'Your training has been saved.'
        ]);
    }

    public function show(Training $training)
    {
        $this->authorize('view',$training);
        return view('trainings.show',compact('training'));
    }

    public function edit(Training $training)
    {
        return view('trainings.edit',compact('training'));
    }

    public function update(Training $training, Request $request)
    {
        // $training->title=$request->title;
        // $training->description=$request->description;
        // $training->save();

        $training->update($request->only('title','description'));

        return redirect()->route('training:index')->with([
            'alert-type'=>'alert-success',
            'alert'=>'Your training has been updated.'
            ]);
    }

    public function delete(Training $training)
    {
        if ($training->attachment!=null) {
            Storage::disk('public')->delete($training->attachment);
        }
        $training->delete();
        return redirect()->route('training:index')->with([
            'alert-type'=>'alert-danger',
            'alert'=>'Your training has been deleted.'
            ]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();
        return view('users.index',compact('users'));
    }
}

resources/views/admin/includes/footer.blade.php
<div class="container-fluid">
    <div class="d-flex align-items-center justify-content-between small">
        <div class="text-muted">Copyright &copy; Your Website 2020</div>
        <div>
            <a href="#">Privacy Policy</a>
            &middot;
            <a href="#">Terms &amp; Conditions</a>
        </div>
    </div>
</div>

resources/views/admin/includes/navbar.blade.php
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="index.html">Start Bootstrap</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Settings</a>
                <a class="dropdown-item" href="#">Activity Log</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="login.html">Logout</a>
            </div>
        </li>
    </ul>
</nav>

resources/views/admin/includes/sidebar.blade.php
<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <div class="sb-sidenav-menu-heading">Core</div>
            <a class="nav-link" href="{{Route('home')}}">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Dashboard
            </a>
            
            <div class="sb-sidenav-menu-heading">Function</div>
            <a class="nav-link" href="{{Route('training:index')}}"> 
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Training List
            </a>
            <a class="nav-link" href="{{Route('training:create')}}">
                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                Create Training
            </a>

            <div class="sb-sidenav-menu-heading">Interface</div>
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                Layouts
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav">
                    <a class="nav-link" href="layout-static.html">Static Navigation</a>
                    <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                </nav>
            </div>
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                Pages
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
            </a>
            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                        Authentication
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="login.html">Login</a>
                            <a class="nav-link" href="register.html">Register</a>
                            <a class="nav-link" href="password.html">Forgot Password</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                        Error
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="401.html">401 Page</a>
                            <a class="nav-link" href="404.html">404 Page</a>
                            <a class="nav-link" href="500.html">500 Page</a>
                        </nav>
                    </div>
                </nav>
            </div>
            <div class="sb-sidenav-menu-heading">Addons</div>
            <a class="nav-link" href="charts.html">
                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                Charts
            </a>
            <a class="nav-link" href="tables.html">
                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                Tables
            </a>
        </div>
    </div>
    <div class="sb-sidenav-footer">
        <div class="small">Logged in as:</div>
        {{auth()->user()->name}}
    </div>
</nav>

resources/views/admin/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="{{asset('admin/css/styles.css')}}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        @include('admin.includes.navbar')
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                @include('admin.includes.sidebar')
            </div>
            <div id="layoutSidenav_content">
                <main>
                    @yield('content')
                </main>
                <footer class="py-4 bg-light mt-auto">
                    @include('admin.includes.footer')
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{{asset('admin/js/scripts.js')}}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{{asset('admin/assets/demo/chart-area-demo.js')}}"></script>
        <script src="{{asset('admin/assets/demo/chart-bar-demo.js')}}"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="{{asset('admin/assets/demo/datatables-demo.js')}}"></script>
    </body>
</html>

resources/views/home.blade.php
@extends('admin.layouts.main')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <a class="nav-link" href="{{Route('training:index')}}">Training List</a>
                        <a class="nav-link" href="{{Route('training:create')}}">Training Create Form</a>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/trainings/create.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Training Create Form</div>
                    <div class="card-body">
                        <form action="" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" name="title" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea name="description" id="description" cols="20" rows="5" class="form-control"></textarea>
                            </div>

                            <div class="form-group">
                                <label>Attachment</label>
                                <input type="file" name="attachment" class="form-control">
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-success">Store My Training</button>
                                <button class="btn btn-danger"><a style="text-decoration:none;color: white" href="{{url()->previous()}}">Back</a></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/trainings/edit.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit Training Form</div>
                    <div class="card-body">
                        <form action="" method="POST">
                            @csrf
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" name="title" class="form-control" value="{{$training->title}}">
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <textarea name="description" id="description" cols="20" rows="5" class="form-control">{{$training->description}}</textarea>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-success" type="submit">Update My Training</button>
                                <button class="btn btn-danger"><a style="text-decoration:none;color: white" href="{{url()->previous()}}">Back</a></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/trainings/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="container-fluid">
        <h1 class="mt-4">Training Module</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Training List</li>
        </ol>
        {{-- @if (session()->has('alert'))
            <div class="alert {{session()->get('alert-type')}}" role="alert">
                {{session()->get('alert')}}
            </div>
        @endif --}}
        <div class="row">
            <div class="col-md-12"> 
                @if (Session::has('alert'))
                    <div class="alert {{Session::get('alert-type')}}" role="alert">
                        {{Session::get('alert')}}
                    </div>
                @endif
                <div class="card">
                    <div class="card-header">
                        Training Index
                        <div class="float-right">
                            <form action="{{Route('training:index')}}" method="GET">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="carian" value="{{request()->get('carian')}}">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="submit">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Bil.</th>
                                    {{-- <th>ID</th> --}}
                                    <th>Title</th>
                                    <th>Creator</th>
                                    <th>Created At</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($trainings as $key=>$training)
                                    <tr>
                                        <td>{{$key+1}}</td>
                                        {{-- <td>{{$training->id}}</td> --}} 
                                        @can('view', $training)
                                            <td><a href="{{Route('training:show',['training'=>$training->id])}}">{{$training->title}}</a></td>
                                        @endcan
                                        @cannot('view', $training)
                                            <td>{{$training->title}}</td> 
                                        @endcannot
                                        <td>{{$training->user->name}}</td>
                                        <td>{{$training->created_at}}</td>
                                        <td>
                                            <div class="btn-group">
                                                @can('update', $training)
                                                    <button class="btn btn-info"><a style="text-decoration:none;color: white" href="{{Route('training:edit',['training'=>$training->id])}}">Edit</a></button>
                                                @endcan
                                                @can('update', $training)
                                                    <button class="btn btn-danger"><a onclick="return confirm('Yakin delete ni?')" style="text-decoration:none;color: white" href="{{Route('training:delete',$training)}}">Delete</a></button>
                                                @endcan
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{
                            $trainings->appends([
                                'carian'=>request()->get('carian')
                            ])->links()
                        }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/trainings/show.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Show Training</div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>Title</label>
                            <input type="text" name="title" class="form-control" value="{{$training->title}}" readonly>
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea name="description" id="description" cols="20" rows="5" class="form-control" readonly>{{$training->description}}</textarea>
                        </div>
                        <div>
                            <button class="btn btn-danger"><a style="text-decoration:none;color: white" href="{{url()->previous()}}">Back</a></button>
                        </div>
                        <div class="form-group">
                            <a href="{{$training->attachment_url}}">View Attachment</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">My Users List</div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Created At</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr>
                                        <td>{{$user->name}}</td>
                                        <td>{{$user->email}}</td>
                                        <td>{{$user->created_at}}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection